#!/bin/sh
# [ KASLD ] Kernel Address Space Layout Derandomization
#
# A collection of various techniques to bypass KASLR and retrieve
# the Linux kernel base virtual address as an unprivileged user.
# ---
# 2019 - <bcoles@gmail.com>

base_dir="$(dirname "$(readlink -f "$0")")"
build="${base_dir}/build"

cd "${base_dir}" || exit 1

echo "[ KASLD ] Kernel Address Space Layout Derandomization"
echo

echo "Kernel release:  $(uname -r)"
echo "Kernel version:  $(uname -v)"
echo "Kernel arch:     $(uname -m)"
echo "Kernel platform: $(uname -i)"

page_size="$(getconf PAGE_SIZE)"
echo "Page size:       ${page_size}"
echo

long_bit="$(getconf LONG_BIT)bit"

echo "Building (${long_bit}) ..."
echo

make "${long_bit}" || exit 1

echo

if [ -x "${build}/default.o" ]; then
  "${build}/default.o"
  echo
fi

if [ -x "${build}/boot-config.o" ]; then
  "${build}/boot-config.o"
  echo
fi

if [ -x "${build}/cmdline.o" ]; then
  "${build}/cmdline.o"
  echo
fi

if [ -x "${build}/bcm_msg_head_struct.o" ]; then
  "${build}/bcm_msg_head_struct.o"
  echo
fi

if [ -x "${build}/kallsyms.o" ]; then
  "${build}/kallsyms.o"
  echo
fi

if [ -x "${build}/sysfs_iscsi_transport_handle.o" ]; then
  "${build}/sysfs_iscsi_transport_handle.o"
  echo
fi

if [ -x "${build}/nf_conntrack.o" ]; then
  "${build}/nf_conntrack.o"
  echo
fi

if [ -x "${build}/perf_event_open.o" ]; then
  "${build}/perf_event_open.o"
  echo
fi

if [ -x "${build}/free_reserved_area_dmesg.o" ]; then
  "${build}/free_reserved_area_dmesg.o"
  echo
fi

if [ -x "${build}/free_reserved_area_syslog.o" ]; then
  "${build}/free_reserved_area_syslog.o"
  echo
fi

if [ -x "${build}/dmesg_backtrace.o" ]; then
  "${build}/dmesg_backtrace.o"
  echo
fi

if [ -x "${build}/dmesg_mem_init_kernel_layout.o" ]; then
  "${build}/dmesg_mem_init_kernel_layout.o"
  echo
fi

if [ -x "${build}/dmesg_mmu_idmap.o" ]; then
  "${build}/dmesg_mmu_idmap.o"
  echo
fi

if [ -x "${build}/pppd_kallsyms.o" ]; then
  "${build}/pppd_kallsyms.o"
  echo
fi

if [ -x "${build}/proc-stat-wchan.o" ]; then
  "${build}/proc-stat-wchan.o"
  echo
fi

if [ -x "${build}/mincore.o" ]; then
  "${build}/mincore.o"
  echo
fi

