#!/bin/sh
# This file is part of KASLD - https://github.com/bcoles/kasld
#
# Check for various known hardware vulnerabilities which can
# be used to read arbitrary kernel memory.
#
# References:
# https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/index.html
# ---
# <bcoles@gmail.com>

echo "[.] For more accurate results, try spectre-meldown-checker:"
echo "    https://github.com/speed47/spectre-meltdown-checker"

echo "[.] Checking /sys/devices/system/cpu/vulnerabilities ..."

grep -sr Vulnerable /sys/devices/system/cpu/vulnerabilities/
echo

if grep -s -q Vulnerable /sys/devices/system/cpu/vulnerabilities/spectre_v1 ; then
  echo "[.] CPU vulnerable to spectre v1 (CVE-2017-5753)"
fi

if grep -s -q Vulnerable /sys/devices/system/cpu/vulnerabilities/spectre_v2 ; then
  echo "[.] CPU vulnerable to spectre v2 (CVE-2017-5715)"
fi

if grep -s -q Vulnerable /sys/devices/system/cpu/vulnerabilities/meltdown ; then
  echo "[.] CPU vulnerable to meltdown (CVE-2017-5754). Try:"
  echo "    https://github.com/paboldin/meltdown-exploit"
fi

if grep -s -q Vulnerable /sys/devices/system/cpu/vulnerabilities/spec_store_bypass ; then
  echo "[.] CPU vulnerable to spectre v4 (CVE-2018-3639)"
fi

if grep -s -q Vulnerable /sys/devices/system/cpu/vulnerabilities/mds ; then
  echo "[.] CPU vulnerable to Microarchitectural Data Sampling (MDS) attacks. Try:"
  echo "    https://github.com/vusec/ridl"
fi

if grep -s -q Vulnerable /sys/devices/system/cpu/vulnerabilities/tsx_async_abort ; then
  echo "[.] CPU vulnerable to TSX asynchronous abort (CVE-2019-11135). Try:"
  echo "    https://github.com/vnik5287/kaslr_tsx_bypass"
fi
