name: clang-format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: clang-format (src)
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '21'
        check-path: src
        only-changed-files: true
    - name: clang-format (tests)
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '21'
        check-path: tests
        only-changed-files: true
