name: clang-format

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - 'src'
          - 'tests'
    steps:
    - uses: actions/checkout@v4
    - name: Run clang-format style check
      uses: jidicula/clang-format-action@v4.18.0
      with:
        clang-format-version: '21'
        check-path: ${{ matrix.path }}
        only-changed-files: true
